plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.148'
}
version = mod_version
group = mod_group_id
base { archivesName = 'atlas' }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
repositories { maven { url = 'https://www.cursemaven.com' }; maven { name = 'JourneyMap'; url = 'https://maven.blamejared.com' } }
neoForge {
    version = project.neo_version
    parchment { mappingsVersion = project.parchment_mappings_version; minecraftVersion = project.parchment_minecraft_version }
    mods { pixelmonradar { sourceSet(sourceSets.main) } }
}
configurations { runtimeClasspath.extendsFrom localRuntime }
dependencies { implementation "curse.maven:pixelmon-389487:${pixelmon_file_id}"; compileOnly "info.journeymap:journeymap-api-neoforge:2.0.0-1.21.1-SNAPSHOT" }
var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [minecraft_version:minecraft_version, minecraft_version_range:minecraft_version_range, neo_version:neo_version, loader_version_range:loader_version_range, mod_id:mod_id, mod_name:mod_name, mod_license:mod_license, mod_version:mod_version]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
