package dev.slithergoh.pixelmonradar.client.screen;
import dev.slithergoh.pixelmonradar.client.*;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import java.util.*;
public final class AtlasClickScreen extends Screen{
 private enum Tab{MODULES,RADAR,BLOCKS,FILTERS,TARGETS,DEX,HUD,SETTINGS}
 private Tab tab=Tab.MODULES;
 private static int savedX=-1,savedY=-1;private static int savedWidth=440,savedHeight=330,opacity=230;
 private int x,y,w=440,h=330,dragX,dragY,scroll;private OreScanner.Category category=OreScanner.Category.USEFUL;
 private boolean dragging,resizing;private int resizeW,resizeH,resizeX,resizeY;private EditBox targetInput;
 private List<PokemonInfo>pokemon=List.of();
 public AtlasClickScreen(){this(false);}public AtlasClickScreen(boolean blocks){super(Component.literal("Atlas ClickGUI"));if(blocks)tab=Tab.BLOCKS;}
 @Override protected void init(){w=Math.min(Math.max(310,RadarSettings.uiWidth),width-12);h=Math.min(Math.max(230,RadarSettings.uiHeight),height-12);opacity=RadarSettings.uiOpacity;x=RadarSettings.uiX<0?(width-w)/2:Math.max(0,Math.min(width-w,RadarSettings.uiX));y=RadarSettings.uiY<0?(height-h)/2:Math.max(0,Math.min(height-h,RadarSettings.uiY));targetInput=new EditBox(font,x+16,y+77,w-96,18,Component.literal("Pokemon name"));targetInput.setHint(Component.literal("Pokemon name..."));targetInput.setMaxLength(50);addRenderableWidget(targetInput);syncInput();}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float pt){}
 @Override public void render(GuiGraphics g,int mx,int my,float pt){pokemon=PokemonScanner.scan();rect(g,x,y,w,h,(opacity<<24)|0x0B1219);rect(g,x,y,w,28,0xFF172A35);g.drawString(font,"ATLAS",x+12,y+10,0xFFFFFFFF,true);g.drawString(font,"DRAG TO MOVE",x+w-94,y+10,0xFF7895A5,false);
  String[]tabs={"MODULES","RADAR","BLOCKS","FILTERS","TARGETS","DEX","HUD","SETTINGS"};int tx=x+8;for(int i=0;i<tabs.length;i++){int tw=(w-16)/8;rect(g,tx+i*tw,y+34,tw-3,24,tab.ordinal()==i?0xFF24546B:0xFF16242E);g.drawCenteredString(font,tabs[i],tx+i*tw+(tw-3)/2,y+42,tab.ordinal()==i?0xFFFFFFFF:0xFF8DA7B4);}
  int top=y+66;g.enableScissor(x+8,top,x+w-8,y+h-26);
  switch(tab){case MODULES->{module(g,top,"Pokemon Radar","Nearby Pokemon and tracking",0);module(g,top+48,"Block ESP","Blocks, loot and ores",1);module(g,top+96,"HUD Overlay","Compact in-game information",2);module(g,top+144,"Rare Alerts","Notifications for rare spawns",3);}
  case RADAR->{g.drawString(font,pokemon.size()+" Pokemon nearby",x+15,top+6,0xFFB4D9E8,false);int max=Math.min(Math.max(0,pokemon.size()-scroll),Math.max(0,(h-117)/34));for(int i=0;i<max;i++){PokemonInfo p=pokemon.get(i+scroll);int yy=top+23+i*34;boolean tracked=RadarSettings.trackedEntityId==p.entityId();rect(g,x+12,yy,w-24,30,tracked?0xFF245341:0xFF17242D);if(p.sprite()!=null)g.blit(p.sprite(),x+18,yy+3,0,0,24,24,24,24);String name=font.plainSubstrByWidth(p.name(),w-156);g.drawString(font,name,x+48,yy+5,p.rare()?0xFFFFC477:0xFFEAF4F7,true);g.drawString(font,"Lv."+p.level()+"  "+Math.round(p.distance())+"m",x+48,yy+17,0xFF92A9B5,false);g.drawString(font,tracked?"TRACKING":"TRACK",x+w-77,yy+11,tracked?0xFF80E9B6:0xFF6EC9EB,false);}} 
  case BLOCKS->{g.drawString(font,"BLOCK SCANNER  "+(RadarSettings.oreEspEnabled?"ENABLED":"DISABLED"),x+15,top+4,0xFFB4D9E8,true);option(g,top+19,"Enable Block ESP",RadarSettings.oreEspEnabled);String[]cats={"USEFUL","ORES","LOOT","PLANTS","UTILITY","ALL"};int cw=(w-24)/6;for(int j=0;j<6;j++){rect(g,x+12+j*cw,top+55,cw-3,22,category.ordinal()==j?0xFF24546B:0xFF17242D);g.drawCenteredString(font,cats[j],x+12+j*cw+(cw-3)/2,top+62,0xFFEAF4F7);}java.util.List<net.minecraft.resources.ResourceLocation> ids=OreScanner.candidates(category);int count=Math.min(Math.max(0,ids.size()-scroll),Math.max(0,(h-225)/30));for(int j=0;j<count;j++){var id=ids.get(j+scroll);String key=id.toString();int yy=top+83+j*30;rect(g,x+12,yy,w-24,27,RadarSettings.selectedOres.contains(key)?0xFF245341:0xFF17242D);g.drawString(font,font.plainSubstrByWidth(id.getPath().replace("_"," "),w-110),x+22,yy+10,0xFFEAF4F7,false);g.drawString(font,RadarSettings.selectedOres.contains(key)?"ON":"OFF",x+w-49,yy+10,0xFF6ED5EF,false);}String[]opts={"GLOW","ICONS","LABELS","ANIM"};boolean[]on={RadarSettings.espGlow,RadarSettings.espIcons,RadarSettings.espLabels,RadarSettings.espAnimation};int ow=(w-24)/4;for(int j=0;j<4;j++){rect(g,x+12+j*ow,y+h-66,ow-4,25,on[j]?0xFF24546B:0xFF17242D);g.drawCenteredString(font,opts[j],x+12+j*ow+(ow-4)/2,y+h-57,0xFFEAF4F7);}}
  case FILTERS->{String[]names={"Shiny only","Legendary","Mythical","Ultra Beast","Paradox","Boss","Not caught","Not seen","Hide owned"};boolean[]values={RadarSettings.shinyOnly,RadarSettings.filterLegendary,RadarSettings.filterMythical,RadarSettings.filterUltraBeast,RadarSettings.filterParadox,RadarSettings.filterBoss,RadarSettings.uncaughtOnly,RadarSettings.unseenOnly,RadarSettings.hideOwnedPokemon};for(int i=scroll;i<names.length&&i<scroll+5;i++)option(g,top+(i-scroll)*35,names[i],values[i]);}
  case TARGETS->{g.drawString(font,"WATCHED POKEMON",x+15,top+1,0xFFB4D9E8,true);g.drawString(font,"ADD",x+w-58,top+15,0xFF6ED5EF,true);int i=0;for(String name:RadarSettings.targetPokemon){if(i>=4)break;int yy=top+39+i*32;rect(g,x+12,yy,w-24,28,0xFF17242D);g.drawString(font,font.plainSubstrByWidth(name,w-105),x+23,yy+10,0xFFEAF4F7,false);g.drawString(font,"REMOVE",x+w-66,yy+10,0xFFFF9B9B,false);i++;}if(i==0)g.drawString(font,"Add a species name to receive spawn pings.",x+15,top+48,0xFF8DA7B4,false);}
  case DEX->{g.drawString(font,"POKEDEX OVERVIEW",x+15,top+8,0xFFB4D9E8,true);try{var dex=((com.pixelmonmod.pixelmon.api.extensions.PixelmonPlayerExtension)minecraft.player).getPokedexNow();if(dex!=null){g.drawString(font,"CAUGHT   "+dex.countCaught(),x+18,top+34,0xFF8FE7B8,true);g.drawString(font,"SEEN   "+dex.countSeen(),x+18,top+56,0xFFFFC477,true);}}catch(Exception ignored){}int n=0;for(PokemonInfo mon:pokemon){if(mon.dexCaught())continue;if(n>=4)break;g.drawString(font,mon.name()+"  "+Math.round(mon.distance())+"m",x+18,top+89+n*24,0xFFEAF4F7,false);n++;}}
  case SETTINGS->{g.drawString(font,"INTERFACE",x+15,top+7,0xFFB4D9E8,true);g.drawString(font,"Opacity  "+Math.round(opacity*100f/255)+"%  (scroll on title)",x+15,top+35,0xFFEAF4F7,false);g.drawString(font,"Drag the title to move; drag the corner to resize.",x+15,top+58,0xFF92A9B5,false);g.drawString(font,"Pokemon scan range: "+RadarSettings.pokemonRange+"m",x+15,top+90,0xFFEAF4F7,false);g.drawString(font,"CLICK TO CHANGE RANGE",x+15,top+110,0xFF6ED5EF,false);g.drawString(font,"Block scan range: "+RadarSettings.oreRange+"m",x+15,top+142,0xFFEAF4F7,false);g.drawString(font,"CLICK TO CHANGE RANGE",x+15,top+162,0xFF6ED5EF,false);option(g,top+194,"Boss spawn alerts",RadarSettings.bossAlertsEnabled);}
  case HUD->{option(g,top,"Radar HUD",RadarSettings.hudEnabled);option(g,top+35,"Rare alerts",RadarSettings.alertsEnabled);option(g,top+70,"Alert sounds",RadarSettings.alertSound);option(g,top+105,"Raid card",RadarSettings.raidHud);option(g,top+140,"Party status",RadarSettings.partyHud);}}
  g.disableScissor();syncInput();if(tab==Tab.TARGETS)super.render(g,mx,my,pt);g.drawString(font,"Drag header | Resize corner | Mouse wheel on header: opacity",x+12,y+h-17,0xFF79919D,false);rect(g,x+w-11,y+h-11,9,9,0xFF66C9EF);}
 private void syncInput(){if(targetInput!=null){targetInput.visible=tab==Tab.TARGETS;targetInput.active=tab==Tab.TARGETS;targetInput.setX(x+16);targetInput.setY(y+80);targetInput.setWidth(w-100);}}private void module(GuiGraphics g,int yy,String name,String sub,int index){rect(g,x+12,yy,w-24,43,0xFF17242D);g.drawString(font,name,x+22,yy+9,0xFFF1F8FB,true);g.drawString(font,sub,x+22,yy+24,0xFF829BA8,false);g.drawString(font,index==1?(RadarSettings.oreEspEnabled?"ON":"OFF"):index==2?(RadarSettings.hudEnabled?"ON":"OFF"):index==3?(RadarSettings.alertsEnabled?"ON":"OFF"):"OPEN",x+w-52,yy+17,0xFF6BD4EF,false);}
 private void option(GuiGraphics g,int yy,String name,boolean on){rect(g,x+12,yy,w-24,30,0xFF17242D);g.drawString(font,name,x+23,yy+11,0xFFE7F2F6,false);rect(g,x+w-52,yy+7,31,16,on?0xFF26775E:0xFF354550);rect(g,x+w-(on?37:49),yy+10,10,10,0xFFF2F7FA);}
 private static void rect(GuiGraphics g,int x,int y,int w,int h,int c){g.fill(x,y,x+w,y+h,c);}
 @Override public boolean mouseClicked(double mx,double my,int button){if(button==0&&mx>=x+w-16&&mx<=x+w&&my>=y+h-16&&my<=y+h){resizing=true;resizeW=w;resizeH=h;resizeX=(int)mx;resizeY=(int)my;return true;}if(my>=y&&my<y+28&&mx>=x&&mx<=x+w&&button==0){dragging=true;dragX=(int)mx-x;dragY=(int)my-y;return true;}if(my>=y+34&&my<y+58&&mx>=x+8&&mx<x+w-8){int i=((int)mx-x-8)/((w-16)/8);if(i>=0&&i<8){tab=Tab.values()[i];scroll=0;syncInput();return true;}}int top=y+66;if(mx<x+12||mx>x+w-12||my<top||my>y+h-26)return super.mouseClicked(mx,my,button);if(tab==Tab.TARGETS&&targetInput.isMouseOver(mx,my)){setFocused(targetInput);targetInput.setFocused(true);return targetInput.mouseClicked(mx,my,button);}if(tab==Tab.TARGETS){targetInput.setFocused(false);setFocused(null);}int i=((int)my-top)/(tab==Tab.MODULES?48:tab==Tab.RADAR?34:35);if(tab==Tab.MODULES&&i>=0&&i<4){if(i==0){tab=Tab.RADAR;syncInput();}else if(i==1){tab=Tab.BLOCKS;scroll=0;}else if(i==2)RadarSettings.hudEnabled=!RadarSettings.hudEnabled;else RadarSettings.alertsEnabled=!RadarSettings.alertsEnabled;}
 else if(tab==Tab.RADAR){int index=((int)my-top-23)/34;if(my>=top+23&&index>=0&&index<pokemon.size()){int id=pokemon.get(index+scroll).entityId();RadarSettings.trackedEntityId=RadarSettings.trackedEntityId==id?-1:id;}}
 else if(tab==Tab.BLOCKS){if(my>=top+19&&my<top+49)RadarSettings.oreEspEnabled=!RadarSettings.oreEspEnabled;else if(my>=top+55&&my<top+77){int ci=((int)mx-x-12)/((w-24)/6);if(ci>=0&&ci<6){category=OreScanner.Category.values()[ci];scroll=0;}}else if(my>=y+h-66&&my<y+h-41){int j=((int)mx-x-12)/((w-24)/4);switch(j){case 0->RadarSettings.espGlow=!RadarSettings.espGlow;case 1->RadarSettings.espIcons=!RadarSettings.espIcons;case 2->RadarSettings.espLabels=!RadarSettings.espLabels;case 3->RadarSettings.espAnimation=!RadarSettings.espAnimation;}}else if(my>=top+83){int idx=((int)my-top-83)/30+scroll;var ids=OreScanner.candidates(category);if(idx>=0&&idx<ids.size()){String id=ids.get(idx).toString();if(!RadarSettings.selectedOres.remove(id))RadarSettings.selectedOres.add(id);}}}
 else if(tab==Tab.SETTINGS){if(my>=top+103&&my<=top+134)RadarSettings.pokemonRange=RadarSettings.pokemonRange>=256?32:RadarSettings.pokemonRange+32;else if(my>=top+155&&my<=top+184)RadarSettings.oreRange=RadarSettings.oreRange>=64?8:RadarSettings.oreRange+8;else if(my>=top+194&&my<=top+224)RadarSettings.bossAlertsEnabled=!RadarSettings.bossAlertsEnabled;}
 else if(tab==Tab.FILTERS){switch(i+scroll){case 0->RadarSettings.shinyOnly=!RadarSettings.shinyOnly;case 1->RadarSettings.filterLegendary=!RadarSettings.filterLegendary;case 2->RadarSettings.filterMythical=!RadarSettings.filterMythical;case 3->RadarSettings.filterUltraBeast=!RadarSettings.filterUltraBeast;case 4->RadarSettings.filterParadox=!RadarSettings.filterParadox;case 5->RadarSettings.filterBoss=!RadarSettings.filterBoss;case 6->RadarSettings.uncaughtOnly=!RadarSettings.uncaughtOnly;case 7->RadarSettings.unseenOnly=!RadarSettings.unseenOnly;case 8->RadarSettings.hideOwnedPokemon=!RadarSettings.hideOwnedPokemon;}}
 else if(tab==Tab.TARGETS){if(my>=top+10&&my<=top+35&&mx>=x+w-80&&mx<=x+w-12){addTarget();}else if(my>=top+39){int n=((int)my-top-39)/32;if(n>=0&&n<4){java.util.List<String> names=new java.util.ArrayList<>(RadarSettings.targetPokemon);if(n<names.size()&&mx>=x+w-86)RadarSettings.targetPokemon.remove(names.get(n));}}}
 else if(tab==Tab.HUD){switch(i){case 0->RadarSettings.hudEnabled=!RadarSettings.hudEnabled;case 1->RadarSettings.alertsEnabled=!RadarSettings.alertsEnabled;case 2->RadarSettings.alertSound=!RadarSettings.alertSound;case 3->RadarSettings.raidHud=!RadarSettings.raidHud;case 4->RadarSettings.partyHud=!RadarSettings.partyHud;}}RadarSettings.save();return true;}
 @Override public boolean mouseDragged(double mx,double my,int b,double dx,double dy){if(resizing){w=Math.max(Math.min(260,width-x),Math.min(width-x,resizeW+(int)mx-resizeX));h=Math.max(Math.min(180,height-y),Math.min(height-y,resizeH+(int)my-resizeY));syncInput();return true;}if(dragging){x=Math.max(0,Math.min(width-w,(int)mx-dragX));y=Math.max(0,Math.min(height-h,(int)my-dragY));return true;}return super.mouseDragged(mx,my,b,dx,dy);}
 @Override public boolean mouseReleased(double mx,double my,int b){if(resizing){resizing=false;savedWidth=w;savedHeight=h;persist();return true;}if(dragging){dragging=false;savedX=x;savedY=y;persist();return true;}return super.mouseReleased(mx,my,b);}
 @Override public boolean mouseScrolled(double mx,double my,double dx,double dy){if(mx>=x&&mx<=x+w&&my>=y&&my<=y+28){opacity=Math.max(105,Math.min(255,opacity+(dy>0?15:-15)));persist();return true;}if(tab==Tab.FILTERS||tab==Tab.RADAR||tab==Tab.BLOCKS){int max=tab==Tab.FILTERS?4:tab==Tab.RADAR?Math.max(0,pokemon.size()-Math.max(1,(h-117)/34)):Math.max(0,OreScanner.candidates(category).size()-Math.max(1,(h-225)/30));scroll=Math.max(0,Math.min(max,scroll+(dy<0?1:-1)));return true;}return super.mouseScrolled(mx,my,dx,dy);}
 @Override public boolean charTyped(char character,int modifiers){if(tab==Tab.TARGETS&&targetInput!=null&&targetInput.isFocused())return targetInput.charTyped(character,modifiers);return super.charTyped(character,modifiers);}
 @Override public boolean keyPressed(int key,int scan,int modifiers){if(tab==Tab.TARGETS&&targetInput!=null&&targetInput.isFocused()){if(key==257||key==335){addTarget();return true;}if(targetInput.keyPressed(key,scan,modifiers))return true;}return super.keyPressed(key,scan,modifiers);}
 private void addTarget(){String name=targetInput.getValue().trim().toLowerCase(java.util.Locale.ROOT);if(!name.isEmpty()){RadarSettings.targetPokemon.add(name);targetInput.setValue("");RadarSettings.save();}}
 private void persist(){RadarSettings.uiX=x;RadarSettings.uiY=y;RadarSettings.uiWidth=w;RadarSettings.uiHeight=h;RadarSettings.uiOpacity=opacity;RadarSettings.save();}
 @Override public void onClose(){persist();super.onClose();}
 @Override public boolean isPauseScreen(){return false;}
}