package dev.slithergoh.pixelmonradar.client.screen;
import dev.slithergoh.pixelmonradar.client.*;import net.minecraft.client.gui.GuiGraphics;import net.minecraft.client.gui.components.EditBox;import net.minecraft.client.gui.screens.Screen;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.network.chat.Component;import net.minecraft.resources.ResourceLocation;import net.minecraft.world.item.ItemStack;import java.util.*;
public final class OreScreen extends Screen{
 private EditBox search;private List<ResourceLocation>blocks=List.of();private int scroll,x,y,w,h;private OreScanner.Category cat=OreScanner.Category.USEFUL;private long opened;private static final OreScanner.Category[]C=OreScanner.Category.values();
 public OreScreen(){super(Component.literal("Atlas Blocks"));}
 @Override protected void init(){w=Math.min(540,width-24);h=Math.min(350,height-24);x=(width-w)/2;y=(height-h)/2;opened=System.currentTimeMillis();search=new EditBox(font,x+43,y+61,220,20,Component.literal("Search"));search.setBordered(false);search.setHint(Component.literal("Search blocks..."));addRenderableWidget(search);refresh();}
 private void refresh(){blocks=OreScanner.candidates(cat);scroll=0;}private List<ResourceLocation>list(){String q=search==null?"":search.getValue().toLowerCase();return blocks.stream().filter(id->id.toString().toLowerCase().contains(q)||name(id).toLowerCase().contains(q)).toList();}private String name(ResourceLocation id){ItemStack s=new ItemStack(BuiltInRegistries.BLOCK.get(id).asItem());return s.isEmpty()?id.getPath().replace('_',' '):s.getHoverName().getString();}
 @Override public void renderBackground(GuiGraphics g,int mx,int my,float pt){}
 @Override public void render(GuiGraphics g,int mx,int my,float pt){float a=Math.min(1,(System.currentTimeMillis()-opened)/200f);int off=(int)((1-(1-(1-a)*(1-a)))*10);round(g,x,y+off,x+w,y+h+off,12,0xF4080E14);round(g,x+1,y+1+off,x+w-1,y+43+off,11,0xFF101C25);g.fill(x+1,y+35+off,x+w-1,y+44+off,0xFF101C25);g.drawString(font,"ATLAS",x+18,y+16+off,0xFFF5FAFC,true);g.drawString(font,"BLOCK SCANNER",x+60,y+16+off,0xFF66C9EF,false);toggle(g,x+w-70,y+13+off,RadarSettings.oreEspEnabled);g.drawString(font,RadarSettings.oreEspEnabled?"LIVE":"OFF",x+w-112,y+18+off,RadarSettings.oreEspEnabled?0xFF82FFC0:0xFF82939B,false);
  round(g,x+16,y+54,x+278,y+84,8,0xFF111D25);g.drawString(font,"⌕",x+25,y+65,0xFF6AC9EC,false);search.setX(x+43);search.setY(y+61);search.setWidth(220);super.render(g,mx,my,pt);
  int tx=x+292;for(int i=0;i<C.length;i++){int ww=36;round(g,tx+i*39,y+57,tx+i*39+ww,y+81,7,C[i]==cat?0xFF214B60:0xFF14232C);g.drawCenteredString(font,icon(C[i]),tx+i*39+ww/2,y+65,C[i]==cat?0xFFFFFFFF:0xFF8298A3);}
  int left=x+16,top=y+96,cardW=(w-44)/2,row=48;List<ResourceLocation>a=list();int max=Math.max(2,((h-132)/row)*2);scroll=Math.min(scroll,Math.max(0,a.size()-max));for(int j=0;j<max&&scroll+j<a.size();j++){ResourceLocation id=a.get(scroll+j);int col=j%2,rr=j/2,xx=left+col*(cardW+12),yy=top+rr*row;boolean on=RadarSettings.selectedOres.contains(id.toString()),hover=mx>=xx&&mx<=xx+cardW&&my>=yy&&my<=yy+40;round(g,xx,yy-(hover?1:0),xx+cardW,yy+40-(hover?1:0),8,on?0xFF1D443A:hover?0xFF192A34:0xFF111D25);ItemStack s=new ItemStack(BuiltInRegistries.BLOCK.get(id).asItem());if(!s.isEmpty())g.renderItem(s,xx+8,yy+11);String n=name(id);if(font.width(n)>cardW-72)n=font.plainSubstrByWidth(n,cardW-80)+"…";g.drawString(font,n,xx+32,yy+9,on?0xFFB2FFD8:0xFFF0F4F6,true);g.drawString(font,on?"ACTIVE":shortId(id),xx+32,yy+23,on?0xFF70EFB0:0xFF718995,false);if(on)round(g,xx+cardW-14,yy+8,xx+cardW-8,yy+32,3,0xFF55D99C);}
  int by=y+h-32;g.drawString(font,RadarSettings.selectedOres.size()+" selected",x+18,by+10,0xFF8299A4,false);pill(g,x+112,by,70,"GLOW",RadarSettings.espGlow);pill(g,x+188,by,70,"ICONS",RadarSettings.espIcons);pill(g,x+264,by,74,"LABELS",RadarSettings.espLabels);pill(g,x+344,by,80,"ANIMATE",RadarSettings.espAnimation);g.drawString(font,RadarSettings.oreRange+"m",x+w-48,by+9,0xFF70D3F4,true);}
 private String shortId(ResourceLocation id){String s=id.getNamespace();return s.length()>10?s.substring(0,10):s;}private String icon(OreScanner.Category c){return switch(c){case USEFUL->"★";case ORES->"◆";case LOOT->"●";case PLANTS->"♣";case UTILITY->"⚙";case ALL->"▦";};}
 private void pill(GuiGraphics g,int xx,int yy,int ww,String s,boolean on){round(g,xx,yy,xx+ww,yy+22,7,on?0xFF214B60:0xFF14232C);g.drawCenteredString(font,s,xx+ww/2,yy+7,on?0xFFFFFFFF:0xFF8298A3);}private void toggle(GuiGraphics g,int xx,int yy,boolean on){round(g,xx,yy,xx+42,yy+18,9,on?0xFF2A765E:0xFF2A3941);int k=on?xx+26:xx+3;round(g,k,yy+3,k+12,yy+15,6,on?0xFFA0FFD4:0xFF9BACB4);}
 @Override public boolean mouseClicked(double mx,double my,int b){if(mx>=x+w-120&&mx<=x+w-15&&my>=y+8&&my<=y+38){RadarSettings.oreEspEnabled=!RadarSettings.oreEspEnabled;RadarSettings.save();return true;}int tx=x+292;for(int i=0;i<C.length;i++)if(mx>=tx+i*39&&mx<=tx+i*39+36&&my>=y+57&&my<=y+81){cat=C[i];refresh();return true;}int left=x+16,top=y+96,cardW=(w-44)/2,row=48,max=Math.max(2,((h-132)/row)*2);List<ResourceLocation>a=list();for(int j=0;j<max&&scroll+j<a.size();j++){int xx=left+(j%2)*(cardW+12),yy=top+(j/2)*row;if(mx>=xx&&mx<=xx+cardW&&my>=yy&&my<=yy+40){String id=a.get(scroll+j).toString();if(!RadarSettings.selectedOres.remove(id))RadarSettings.selectedOres.add(id);RadarSettings.save();return true;}}int by=y+h-32;if(my>=by&&my<=by+22){if(mx>=x+112&&mx<=x+182)RadarSettings.espGlow=!RadarSettings.espGlow;else if(mx>=x+188&&mx<=x+258)RadarSettings.espIcons=!RadarSettings.espIcons;else if(mx>=x+264&&mx<=x+338)RadarSettings.espLabels=!RadarSettings.espLabels;else if(mx>=x+344&&mx<=x+424)RadarSettings.espAnimation=!RadarSettings.espAnimation;else return super.mouseClicked(mx,my,b);RadarSettings.save();return true;}return super.mouseClicked(mx,my,b);}
 @Override public boolean mouseScrolled(double mx,double my,double sx,double sy){List<ResourceLocation>a=list();int max=Math.max(2,((h-132)/48)*2);scroll=Math.max(0,Math.min(Math.max(0,a.size()-max),scroll+(sy<0?2:-2)));return true;}private static void round(GuiGraphics g,int l,int t,int r,int b,int rad,int c){if(r<=l||b<=t)return;rad=Math.max(1,Math.min(rad,Math.min((r-l)/2,(b-t)/2)));g.fill(l+rad,t,r-rad,b,c);g.fill(l,t+rad,r,b-rad,c);for(int i=0;i<rad;i++){int in=(int)Math.ceil(rad-Math.sqrt(Math.max(0,rad*rad-(rad-i)*(rad-i))));g.fill(l+in,t+i,r-in,b-i,c);}}@Override public void onClose(){RadarSettings.save();super.onClose();}@Override public boolean isPauseScreen(){return false;}}
