package dev.slithergoh.pixelmonradar.client;
import net.minecraft.client.Minecraft;import net.minecraft.core.BlockPos;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.resources.ResourceLocation;import net.minecraft.world.level.block.Block;import java.util.*;
public final class OreScanner{private OreScanner(){}private static volatile List<BlockPos>cached=List.of();private static final LinkedHashSet<BlockPos>found=new LinkedHashSet<>();private static final HashSet<Block>selectedBlocks=new HashSet<>();private static BlockPos center=BlockPos.ZERO;private static int range=-1,selectionHash,x,y,z,minX,maxX,minY,maxY,minZ,maxZ;private static boolean scanning;
public enum Category{USEFUL,ORES,LOOT,PLANTS,UTILITY,ALL}
public static List<ResourceLocation>candidates(){return candidates(Category.ALL);}public static List<ResourceLocation>candidates(Category cat){ArrayList<ResourceLocation>out=new ArrayList<>();for(ResourceLocation id:BuiltInRegistries.BLOCK.keySet())if(matches(id,cat))out.add(id);out.sort(Comparator.comparing(ResourceLocation::toString));return out;}
private static boolean matches(ResourceLocation id,Category c){String n=id.toString().toLowerCase(),p=id.getPath().toLowerCase();boolean ore=p.contains("ore")||p.contains("bauxite")||p.contains("ruby")||p.contains("sapphire")||p.contains("platinum")||p.contains("silver")||p.contains("silicon")||p.contains("crystal");boolean loot=p.contains("pokeloot")||p.contains("poke_loot")||p.contains("pokeball")||p.contains("poke_ball")||p.contains("pokestop")||p.contains("poke_stop")||p.contains("grotto")||p.contains("loot");boolean plant=p.contains("apricorn")||p.contains("berry")||p.contains("plant")||p.contains("crop");boolean util=p.contains("healer")||p.contains("pc")||p.contains("trade")||p.contains("fossil")||p.contains("den")||p.contains("shrine")||p.contains("machine");return switch(c){case ORES->ore;case LOOT->loot;case PLANTS->plant;case UTILITY->util;case USEFUL->n.startsWith("pixelmon:")&&(loot||ore||util);case ALL->true;};}
public static List<BlockPos>scan(){return cached;}
public static void tick(){Minecraft mc=Minecraft.getInstance();if(mc.level==null||mc.player==null||!RadarSettings.oreEspEnabled||RadarSettings.selectedOres.isEmpty()){if(RadarSettings.selectedOres.isEmpty())cached=List.of();scanning=false;return;}BlockPos c=mc.player.blockPosition();int r=RadarSettings.oreRange,h=RadarSettings.selectedOres.hashCode();if(!scanning||range!=r||selectionHash!=h||c.distSqr(center)>64)start(mc,c,r,h);step(mc,9000);}
private static void start(Minecraft mc,BlockPos c,int r,int h){center=c;range=r;selectionHash=h;selectedBlocks.clear();for(String s:RadarSettings.selectedOres){ResourceLocation id=ResourceLocation.tryParse(s);if(id!=null)selectedBlocks.add(BuiltInRegistries.BLOCK.get(id));}found.clear();double rr=(double)r*r;for(BlockPos p:cached)if(p.distSqr(c)<=rr&&mc.level.hasChunkAt(p)&&selectedBlocks.contains(mc.level.getBlockState(p).getBlock()))found.add(p);minX=c.getX()-r;maxX=c.getX()+r;minZ=c.getZ()-r;maxZ=c.getZ()+r;minY=Math.max(mc.level.getMinBuildHeight(),c.getY()-r);maxY=Math.min(mc.level.getMaxBuildHeight()-1,c.getY()+r);x=minX;y=minY;z=minZ;scanning=true;publish();}
private static void step(Minecraft mc,int budget){for(int i=0;i<budget&&scanning;i++){int dx=x-center.getX(),dy=y-center.getY(),dz=z-center.getZ();if((long)dx*dx+(long)dy*dy+(long)dz*dz<=(long)range*range){BlockPos p=new BlockPos(x,y,z);if(mc.level.hasChunkAt(p)&&selectedBlocks.contains(mc.level.getBlockState(p).getBlock()))found.add(p);}advance();}publish();}
private static void advance(){x++;if(x>maxX){x=minX;z++;if(z>maxZ){z=minZ;y++;if(y>maxY)scanning=false;}}}
private static void publish(){ArrayList<BlockPos>list=new ArrayList<>(found);list.removeIf(p->p.distSqr(center)>(double)range*range);list.sort(Comparator.comparingDouble(p->p.distSqr(center)));if(list.size()>2500)list.subList(2500,list.size()).clear();cached=List.copyOf(list);}
}