package dev.slithergoh.pixelmonradar.client;
import net.minecraft.client.Minecraft;import net.minecraft.core.BlockPos;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.resources.ResourceLocation;import net.minecraft.world.level.block.Block;import java.util.*;
public final class OreScanner{private OreScanner(){}private static volatile List<BlockPos>cached=List.of();private static final LinkedHashSet<BlockPos>working=new LinkedHashSet<>();private static final ArrayList<BlockPos>order=new ArrayList<>();private static final HashSet<Block>selectedBlocks=new HashSet<>();private static BlockPos center=BlockPos.ZERO;private static int range=-1,selectionHash,index;private static boolean scanning;
 public enum Category{USEFUL,ORES,LOOT,PLANTS,UTILITY,ALL}
 public static List<ResourceLocation>candidates(){return candidates(Category.ALL);}public static List<ResourceLocation>candidates(Category cat){ArrayList<ResourceLocation>out=new ArrayList<>();for(ResourceLocation id:BuiltInRegistries.BLOCK.keySet())if(matches(id,cat))out.add(id);out.sort(Comparator.comparing(ResourceLocation::toString));return out;}
 private static boolean matches(ResourceLocation id,Category c){String n=id.toString().toLowerCase(),p=id.getPath().toLowerCase();boolean ore=p.contains("ore")||p.contains("bauxite")||p.contains("ruby")||p.contains("sapphire")||p.contains("platinum")||p.contains("silver")||p.contains("silicon")||p.contains("crystal");boolean loot=p.contains("pokeloot")||p.contains("poke_loot")||p.contains("pokeball")||p.contains("poke_ball")||p.contains("pokestop")||p.contains("poke_stop")||p.contains("grotto")||p.contains("loot");boolean plant=p.contains("apricorn")||p.contains("berry")||p.contains("plant")||p.contains("crop");boolean util=p.contains("healer")||p.contains("pc")||p.contains("trade")||p.contains("fossil")||p.contains("den")||p.contains("shrine")||p.contains("machine");return switch(c){case ORES->ore;case LOOT->loot;case PLANTS->plant;case UTILITY->util;case USEFUL->n.startsWith("pixelmon:")&&(loot||ore||util);case ALL->true;};}
 public static List<BlockPos>scan(){Minecraft mc=Minecraft.getInstance();if(mc.level==null||mc.player==null||RadarSettings.selectedOres.isEmpty()){cached=List.of();scanning=false;return cached;}BlockPos c=mc.player.blockPosition();int r=RadarSettings.oreRange,h=RadarSettings.selectedOres.hashCode();if(range!=r||selectionHash!=h||c.distSqr(center)>16)start(mc,c,r,h);return cached;}
 public static void tick(){Minecraft mc=Minecraft.getInstance();if(mc.level==null||mc.player==null||!RadarSettings.oreEspEnabled)return;scan();if(scanning)step(mc,7000);}
 private static void start(Minecraft mc,BlockPos c,int r,int h){center=c;range=r;selectionHash=h;index=0;working.clear();selectedBlocks.clear();for(String s:RadarSettings.selectedOres){ResourceLocation id=ResourceLocation.tryParse(s);if(id!=null)selectedBlocks.add(BuiltInRegistries.BLOCK.get(id));}order.clear();for(int dy=-r;dy<=r;dy++)for(int dz=-r;dz<=r;dz++)for(int dx=-r;dx<=r;dx++){int d2=dx*dx+dy*dy+dz*dz;if(d2<=r*r){int yy=c.getY()+dy;if(yy>=mc.level.getMinBuildHeight()&&yy<mc.level.getMaxBuildHeight())order.add(new BlockPos(c.getX()+dx,yy,c.getZ()+dz));}}order.sort(Comparator.comparingDouble(p->p.distSqr(c)));scanning=true;pruneOld(mc);}
 private static void pruneOld(Minecraft mc){ArrayList<BlockPos>keep=new ArrayList<>();double rr=(double)range*range;for(BlockPos p:cached)if(p.distSqr(center)<=rr&&mc.level.hasChunkAt(p)&&selectedBlocks.contains(mc.level.getBlockState(p).getBlock()))keep.add(p);keep.sort(Comparator.comparingDouble(p->p.distSqr(center)));cached=List.copyOf(keep);working.addAll(keep);}
 private static void step(Minecraft mc,int budget){int end=Math.min(order.size(),index+budget);for(;index<end;index++){BlockPos p=order.get(index);if(!mc.level.hasChunkAt(p))continue;Block b=mc.level.getBlockState(p).getBlock();if(selectedBlocks.contains(b))working.add(p);}if(index>=order.size())finish();else publishProgress();}
 private static void publishProgress(){if(working.isEmpty())return;ArrayList<BlockPos>fresh=new ArrayList<>(working);fresh.sort(Comparator.comparingDouble(p->p.distSqr(center)));if(fresh.size()>2500)fresh.subList(2500,fresh.size()).clear();cached=List.copyOf(fresh);}
 private static void finish(){ArrayList<BlockPos>fresh=new ArrayList<>(working);fresh.sort(Comparator.comparingDouble(p->p.distSqr(center)));if(fresh.size()>2500)fresh.subList(2500,fresh.size()).clear();cached=List.copyOf(fresh);order.clear();working.clear();scanning=false;}
}