package dev.slithergoh.pixelmonradar.client;
import net.minecraft.client.Minecraft;import net.minecraft.core.BlockPos;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.resources.ResourceLocation;import net.minecraft.world.level.block.Block;import java.util.*;
public final class OreScanner{private OreScanner(){}private static volatile List<BlockPos>cached=List.of();private static final ArrayList<BlockPos>working=new ArrayList<>();private static BlockPos center=BlockPos.ZERO;private static int range=-1,selectionHash;private static int x,y,z,minX,maxX,minY,maxY,minZ,maxZ;private static boolean scanning;
 public enum Category{USEFUL,ORES,LOOT,PLANTS,UTILITY,ALL}
 public static List<ResourceLocation>candidates(){return candidates(Category.ALL);}public static List<ResourceLocation>candidates(Category cat){ArrayList<ResourceLocation>out=new ArrayList<>();for(ResourceLocation id:BuiltInRegistries.BLOCK.keySet())if(matches(id,cat))out.add(id);out.sort(Comparator.comparing(ResourceLocation::toString));return out;}
 private static boolean matches(ResourceLocation id,Category c){String n=id.toString().toLowerCase(),p=id.getPath().toLowerCase();boolean ore=p.contains("ore")||p.contains("bauxite")||p.contains("ruby")||p.contains("sapphire")||p.contains("platinum")||p.contains("silver")||p.contains("silicon")||p.contains("crystal");boolean loot=p.contains("pokeloot")||p.contains("poke_loot")||p.contains("pokeball")||p.contains("poke_ball")||p.contains("pokestop")||p.contains("poke_stop")||p.contains("grotto")||p.contains("loot");boolean plant=p.contains("apricorn")||p.contains("berry")||p.contains("plant")||p.contains("crop");boolean util=p.contains("healer")||p.contains("pc")||p.contains("trade")||p.contains("fossil")||p.contains("den")||p.contains("shrine")||p.contains("machine");return switch(c){case ORES->ore;case LOOT->loot;case PLANTS->plant;case UTILITY->util;case USEFUL->n.startsWith("pixelmon:")&&(loot||ore||util);case ALL->true;};}
 public static List<BlockPos>scan(){Minecraft mc=Minecraft.getInstance();if(mc.level==null||mc.player==null||RadarSettings.selectedOres.isEmpty()){cached=List.of();scanning=false;return cached;}BlockPos c=mc.player.blockPosition();int r=RadarSettings.oreRange,h=RadarSettings.selectedOres.hashCode();if(!scanning&&(range!=r||selectionHash!=h||c.distManhattan(center)>8))start(mc,c,r,h);if(scanning)step(mc,12000);return cached;}
 private static void start(Minecraft mc,BlockPos c,int r,int h){center=c;range=r;selectionHash=h;working.clear();minX=c.getX()-r;maxX=c.getX()+r;minZ=c.getZ()-r;maxZ=c.getZ()+r;minY=Math.max(mc.level.getMinBuildHeight(),c.getY()-r);maxY=Math.min(mc.level.getMaxBuildHeight()-1,c.getY()+r);x=minX;y=minY;z=minZ;scanning=true;}
 private static void step(Minecraft mc,int budget){for(int i=0;i<budget&&scanning;i++){BlockPos p=new BlockPos(x,y,z);if(mc.level.hasChunkAt(p)&&p.distSqr(center)<=((double)range*range)){Block b=mc.level.getBlockState(p).getBlock();ResourceLocation id=BuiltInRegistries.BLOCK.getKey(b);if(RadarSettings.selectedOres.contains(id.toString()))working.add(p);}if(++x>maxX){x=minX;if(++z>maxZ){z=minZ;if(++y>maxY)finish();}}if(working.size()>=2500)finish();}}
 private static void finish(){working.sort(Comparator.comparingDouble(p->p.distSqr(center)));cached=List.copyOf(working);scanning=false;}
}