package dev.slithergoh.pixelmonradar.client;
import com.mojang.blaze3d.vertex.*;import com.pixelmonmod.pixelmon.entities.pixelmon.PixelmonEntity;import net.minecraft.client.Minecraft;import net.minecraft.client.renderer.*;import net.minecraft.core.BlockPos;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.resources.ResourceLocation;import net.minecraft.world.phys.Vec3;import net.neoforged.api.distmarker.Dist;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.neoforge.client.event.RenderLevelStageEvent;import java.util.OptionalDouble;
@EventBusSubscriber(modid="pixelmonradar",value=Dist.CLIENT)
public final class OreWorldRenderer{
 private static final RenderType ESP_LINES=EspRenderType.linesNoDepth();
 @SubscribeEvent public static void render(RenderLevelStageEvent e){
  if(e.getStage()!=RenderLevelStageEvent.Stage.AFTER_CUTOUT_MIPPED_BLOCKS_BLOCKS)return;
  if(!RadarSettings.oreEspEnabled&&RadarSettings.trackedEntityId==-1)return;
  Minecraft mc=Minecraft.getInstance();if(mc.level==null||mc.player==null)return;
  Vec3 cam=mc.gameRenderer.getMainCamera().getPosition();PoseStack ps=e.getPoseStack();ps.pushPose();ps.translate(-cam.x,-cam.y,-cam.z);
  MultiBufferSource.BufferSource bs=mc.renderBuffers().bufferSource();VertexConsumer vc=bs.getBuffer(ESP_LINES);
  if(RadarSettings.oreEspEnabled){int count=0;for(BlockPos p:OreScanner.scan()){if(count++>=1200)break;ResourceLocation id=BuiltInRegistries.BLOCK.getKey(mc.level.getBlockState(p).getBlock());float[]c=color(id);LevelRenderer.renderLineBox(ps,vc,p.getX()-.002,p.getY()-.002,p.getZ()-.002,p.getX()+1.002,p.getY()+1.002,p.getZ()+1.002,c[0],c[1],c[2],1f,c[0],c[1],c[2]);}}
  for(PokemonInfo rare:PokemonScanner.scan())if(rare.rare()){var re=mc.level.getEntity(rare.entityId());if(re instanceof PixelmonEntity rp){var b=rp.getBoundingBox().inflate(.08);float[]c=rare.shiny()?new float[]{1f,.82f,.18f}:rare.legendary()||rare.mythical()?new float[]{1f,.55f,.15f}:rare.boss()?new float[]{1f,.2f,.12f}:new float[]{.7f,.25f,1f};LevelRenderer.renderLineBox(ps,vc,b.minX,b.minY,b.minZ,b.maxX,b.maxY,b.maxZ,c[0],c[1],c[2],1f,c[0],c[1],c[2]);}}
  if(RadarSettings.trackedEntityId!=-1){var entity=mc.level.getEntity(RadarSettings.trackedEntityId);if(entity instanceof PixelmonEntity pokemon){var b=pokemon.getBoundingBox().inflate(.12);boolean shiny=pokemon.getPokemon()!=null&&pokemon.getPokemon().isShiny();float rr=shiny?1f:.2f,gg=shiny?.82f:.85f,bb=shiny?.18f:1f;LevelRenderer.renderLineBox(ps,vc,b.minX,b.minY,b.minZ,b.maxX,b.maxY,b.maxZ,rr,gg,bb,1f,rr,gg,bb);}}
  bs.endBatch(ESP_LINES);ps.popPose();
 }
 private static final class EspRenderType extends RenderType{private EspRenderType(String n,VertexFormat f,VertexFormat.Mode m,int b,boolean a,boolean c,Runnable s,Runnable e){super(n,f,m,b,a,c,s,e);}static RenderType linesNoDepth(){CompositeState state=CompositeState.builder().setShaderState(RENDERTYPE_LINES_SHADER).setLineState(new LineStateShard(OptionalDouble.of(2.0))).setLayeringState(VIEW_OFFSET_Z_LAYERING).setTransparencyState(TRANSLUCENT_TRANSPARENCY).setOutputState(ITEM_ENTITY_TARGET).setWriteMaskState(COLOR_WRITE).setCullState(NO_CULL).setDepthTestState(NO_DEPTH_TEST).createCompositeState(false);return create("atlas_stable_esp_lines",DefaultVertexFormat.POSITION_COLOR_NORMAL,VertexFormat.Mode.LINES,256,state);}}
 private static float[]color(ResourceLocation id){String p=id.getPath();if(p.contains("pokestop")||p.contains("poke_stop"))return new float[]{.15f,.75f,1f};if(p.contains("pokeloot")||p.contains("poke_loot")||p.contains("pokeball")||p.contains("poke_ball"))return new float[]{1f,.2f,.25f};if(p.contains("diamond")||p.contains("crystal"))return new float[]{.2f,1f,1f};if(p.contains("emerald"))return new float[]{.2f,1f,.35f};if(p.contains("redstone")||p.contains("ruby"))return new float[]{1f,.15f,.15f};if(p.contains("lapis")||p.contains("sapphire"))return new float[]{.2f,.4f,1f};if(p.contains("gold"))return new float[]{1f,.8f,.1f};if(p.contains("iron")||p.contains("silver")||p.contains("platinum"))return new float[]{.9f,.9f,.9f};if(p.contains("copper")||p.contains("bauxite"))return new float[]{1f,.45f,.18f};if(p.contains("coal"))return new float[]{.55f,.55f,.55f};return new float[]{1f,.3f,.8f};}
}