package dev.slithergoh.pixelmonradar.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import net.neoforged.fml.loading.FMLPaths;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashSet;
import java.util.Set;

public final class RadarSettings {
 private RadarSettings(){} private static final Gson GSON=new GsonBuilder().setPrettyPrinting().create(); private static final Path FILE=FMLPaths.CONFIGDIR.get().resolve("pixelmonradar.json");
 public static boolean hudEnabled=true,oreEspEnabled=false,shinyOnly=false,rareOnly=false,filterLegendary=false,filterMythical=false,filterUltraBeast=false,filterParadox=false,filterBoss=false,hideOwnedPokemon=true,hideClaimedLoot=true,uncaughtOnly=false,unseenOnly=false,raidHud=true,partyHud=true,newDexAlerts=true,alertsEnabled=true,alertSound=true,espGlow=true,espIcons=true,espLabels=true,espAnimation=true;
 public static int hudX=6,hudY=6,partyX=7,partyY=145,raidX=-1,raidY=7,trackerX=-1,trackerY=7;public static int uiX=-1,uiY=-1,uiWidth=440,uiHeight=330,uiOpacity=230;public static boolean bossAlertsEnabled=false; public static int pokemonRange=128,oreRange=24,espDetailRange=24,espMaxIcons=24,trackedEntityId=-1; public static String search=""; public static final Set<String> targetPokemon=new LinkedHashSet<>(); public static SortMode sortMode=SortMode.DISTANCE; public static final Set<String> selectedOres=new LinkedHashSet<>();
 public enum SortMode{DISTANCE,LEVEL,NAME,RARITY}
 private record Data(boolean hudEnabled,boolean oreEspEnabled,int pokemonRange,int oreRange,boolean shinyOnly,boolean rareOnly,boolean alertsEnabled,boolean alertSound,SortMode sortMode,Set<String> selectedOres,Boolean espGlow,Boolean espIcons,Boolean espLabels,Boolean espAnimation,Integer espDetailRange,Integer espMaxIcons,Boolean filterLegendary,Boolean filterMythical,Boolean filterUltraBeast,Boolean filterParadox,Boolean filterBoss,Boolean hideOwnedPokemon,Boolean hideClaimedLoot,Boolean uncaughtOnly,Boolean unseenOnly,Boolean raidHud,Boolean partyHud,Boolean newDexAlerts,Set<String> targetPokemon,Boolean bossAlertsEnabled,Integer uiX,Integer uiY,Integer uiWidth,Integer uiHeight,Integer uiOpacity,Integer hudX,Integer hudY,Integer partyX,Integer partyY,Integer raidX,Integer raidY,Integer trackerX,Integer trackerY){}
 public static void load(){try{if(!Files.exists(FILE))return;Data d=GSON.fromJson(Files.readString(FILE),Data.class);if(d==null)return;hudEnabled=d.hudEnabled;oreEspEnabled=d.oreEspEnabled;pokemonRange=d.pokemonRange;oreRange=d.oreRange;shinyOnly=d.shinyOnly;rareOnly=d.rareOnly;alertsEnabled=d.alertsEnabled;alertSound=d.alertSound;sortMode=d.sortMode==null?SortMode.DISTANCE:d.sortMode;selectedOres.clear();if(d.selectedOres!=null)selectedOres.addAll(d.selectedOres);if(d.espGlow!=null)espGlow=d.espGlow;if(d.espIcons!=null)espIcons=d.espIcons;if(d.espLabels!=null)espLabels=d.espLabels;if(d.espAnimation!=null)espAnimation=d.espAnimation;if(d.espDetailRange!=null)espDetailRange=d.espDetailRange;if(d.espMaxIcons!=null)espMaxIcons=d.espMaxIcons;if(d.filterLegendary!=null)filterLegendary=d.filterLegendary;if(d.filterMythical!=null)filterMythical=d.filterMythical;if(d.filterUltraBeast!=null)filterUltraBeast=d.filterUltraBeast;if(d.filterParadox!=null)filterParadox=d.filterParadox;if(d.filterBoss!=null)filterBoss=d.filterBoss;if(d.hideOwnedPokemon!=null)hideOwnedPokemon=d.hideOwnedPokemon;if(d.hideClaimedLoot!=null)hideClaimedLoot=d.hideClaimedLoot;if(d.uncaughtOnly!=null)uncaughtOnly=d.uncaughtOnly;if(d.unseenOnly!=null)unseenOnly=d.unseenOnly;if(d.raidHud!=null)raidHud=d.raidHud;if(d.partyHud!=null)partyHud=d.partyHud;if(d.newDexAlerts!=null)newDexAlerts=d.newDexAlerts;if(d.bossAlertsEnabled!=null)bossAlertsEnabled=d.bossAlertsEnabled;if(d.uiX!=null)uiX=d.uiX;if(d.uiY!=null)uiY=d.uiY;if(d.uiWidth!=null)uiWidth=d.uiWidth;if(d.uiHeight!=null)uiHeight=d.uiHeight;if(d.uiOpacity!=null)uiOpacity=d.uiOpacity;if(d.hudX!=null)hudX=d.hudX;if(d.hudY!=null)hudY=d.hudY;if(d.partyX!=null)partyX=d.partyX;if(d.partyY!=null)partyY=d.partyY;if(d.raidX!=null)raidX=d.raidX;if(d.raidY!=null)raidY=d.raidY;if(d.trackerX!=null)trackerX=d.trackerX;if(d.trackerY!=null)trackerY=d.trackerY;if(d.targetPokemon!=null){targetPokemon.clear();targetPokemon.addAll(d.targetPokemon);}}catch(Exception ignored){}}
 public static void save(){try{Files.createDirectories(FILE.getParent());Files.writeString(FILE,GSON.toJson(new Data(hudEnabled,oreEspEnabled,pokemonRange,oreRange,shinyOnly,rareOnly,alertsEnabled,alertSound,sortMode,new LinkedHashSet<>(selectedOres),espGlow,espIcons,espLabels,espAnimation,espDetailRange,espMaxIcons,filterLegendary,filterMythical,filterUltraBeast,filterParadox,filterBoss,hideOwnedPokemon,hideClaimedLoot,uncaughtOnly,unseenOnly,raidHud,partyHud,newDexAlerts,new LinkedHashSet<>(targetPokemon),bossAlertsEnabled,uiX,uiY,uiWidth,uiHeight,uiOpacity,hudX,hudY,partyX,partyY,raidX,raidY,trackerX,trackerY)));}catch(Exception ignored){}}
}
