modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="slithergoh"
logoFile="atlas.png"
description='''Useful exploration and world interaction utilities.'''
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="pixelmon"
type="required"
versionRange="[9.4.1,9.5.0)"
ordering="AFTER"
side="CLIENT"
